# Site settings
title: Cat Apps
email: letsdoit@catapps.co.uk
url: https://catapps.co.uk
description: "Cat Apps specializes in bespoke React-Native Web & Mobile solutions tailored to your business needs. Transform your visions into digital realities with us."
keywords: "React-Native Development, Mobile App Development, Web App Development, Custom Software Solutions, SME Digital Transformation, Bespoke Business Applications, Industry Visionaries, Digital Journey, App Aspirations, Software Consultation"
skills: "Your App Ideas Ready for Launch"
meta_author: Catalin Magirescu

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: catapps

formspree_atribute: f/xvojrnok

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 222222
  primary-rgb: "34,34,34"
  secondary: 333333
  secondary-dark: 444444

# Footer settings
footer:
  copyright: Cat Apps
  location: Where?
  social: What?
  credits: When?

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://linkedin.com/company/catapps
  - title: facebook
    url: https://www.facebook.com/CatApps.co.uk
  - title: github
    url: http://github.com/Cat-Apps

# Postal address (add as many lines as necessary)
address:
  - line: London,
  - line: Northamptonshire
  - line: and mostly online

# Credits content
credits: 'Monday - Friday: 9:00 AM to 5:00 <br/>PM Weekends & Bank Holidays: Closed'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
